# Generated by Django 4.2.2 on 2023-06-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HardFrame', '0002_alter_oferta_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_Produc', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('enlace', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='oferta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='oferta'),
        ),
    ]
