# Generated by Django 4.2.2 on 2023-06-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HardFrame', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='componente',
            fields=[
                ('id_Produc', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('imagen', models.ImageField(null=True, upload_to='componentes')),
                ('enlace', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='software',
            fields=[
                ('id_Produc', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('imagen', models.ImageField(null=True, upload_to='softwares')),
                ('enlace', models.URLField()),
            ],
        ),
    ]
