# Generated by Django 4.2.2 on 2023-07-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HardFrame', '0005_componente_software'),
    ]

    operations = [
        migrations.DeleteModel(
            name='producto',
        ),
    ]
