# Generated by Django 4.2.2 on 2023-07-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HardFrame', '0006_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='periferico',
            fields=[
                ('id_Produc', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('imagen', models.ImageField(null=True, upload_to='perifericos')),
                ('enlace', models.URLField()),
            ],
        ),
    ]
