# Generated by Django 4.2.2 on 2023-07-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HardFrame', '0007_periferico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periferico',
            name='id_Produc',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
