# Generated by Django 4.2.2 on 2023-07-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HardFrame', '0008_alter_periferico_id_produc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='id_Produc',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='id_Produc',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='software',
            name='id_Produc',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
